eureka:
    client:
        registerWithEureka: true
        service-url:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    instance:
        prefer-ip-address: true

spring:
    config:
        activate:
            on-profile: default
    jpa:
        database: h2
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./mydatabase
        username: sa
        password: 
    h2:
        console:
            enabled: true
            path: /h2