spring:
  application:
    name: ms-item
  graphql:
    graphiql:
      enabled: true

server:
  port: 8085


info:
  app:
    name: ms-item
    description: Un microservicio para manejar la lógica de los items en el sistema. Usa un servicio GraphQL para interactuar con la base de datos.

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE