spring:
  application:
    name: ms-orden

server:
  port: 8086


info:
  app:
    name: ms-orden
    description: Un microservicio para manejar la lógica de las ordenes en el sistema

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
    info:
        env:
            enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE